name: PROJECT-NAME
recipe: wordpress
config:
  webroot: web


services:
  appserver:
    build:
      - cd $LANDO_MOUNT && composer install
  node:
    type: node:6.10
    # build:
    #   - "cd $LANDO_MOUNT/src/themes/[CLIENT-THEME] && npm install"

    # Uncomment the following to use brwoserSync.
    # overrides:
    #   services:
    #     ports:
    #       - 3000:3000
    #       - 3001:3001
    globals:
      gulp-cli: "latest"
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
